model_params:
  name: 'ConditionalVAE'
  in_channels: 12
  latent_dim: 4
  num_classes: 16

exp_params:
  dataset: cosa
  data_path: "/scratch/qijing.huang/matchlib/cmod/unittests/HybridRouterTopMeshTCGB"
  img_size: 12
  batch_size: 16 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  manual_seed: 1265
