model_params:
  name: 'VanillaVAENorm'
  in_channels: 7
  latent_dim: 4

exp_params:
  dataset: cosa
  data_path: "/scratch/qijing.huang/matchlib/cmod/unittests/HybridRouterTopMeshTCGB"
  img_size: 7
  batch_size: 16 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 50
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "VanillaVAENorm"
  manual_seed: 1265
