model_params:
  name: 'VanillaVAE'
  in_channels: 10
  latent_dim: 4

exp_params:
  dataset: cosa
  data_path: "/scratch/qijing.huang/matchlib/cmod/unittests/HybridRouterTopMeshTCGB"
  img_size: 10
  batch_size: 16 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
